DOMAIN = "moscow_bus_tracker"

CONF_API_KEY = "api_key"
CONF_UPDATE_INTERVAL = "update_interval"
CONF_UPCOMING_COUNT = "upcoming_count"
CONF_NEWDAY_SHIFT = "newday_shift"
CONF_MISSED_INTERVAL = "missed_interval"
CONF_MISSED_COLOR = "missed_color"
CONF_MISSED_BADGE = "missed_badge"
CONF_ARRIVING_INTERVAL = "arriving_interval"
CONF_ARRIVING_COLOR = "arriving_color"
CONF_ARRIVING_BADGE = "arriving_badge"
CONF_DEFAULT_COLOR = "default_color"

CONF_ROUTE_NUMBER = "route_number"
CONF_STOPS_QUERY = "stops_query"

CONF_ROUTE_ID = "route_id"
CONF_STOP_ID = "stop_id"

CONF_ROUTE_TYPE = "route_type"
CONF_ROUTE_TYPE_NAME = "route_type_name"
CONF_ROUTE_SHORT_NAME = "route_short_name"
CONF_ROUTE_LONG_NAME = "route_long_name"
CONF_STOP_NAME = "stop_name"

DEFAULT_UPDATE_INTERVAL_MINUTES = 60
DEFAULT_UPCOMING_COUNT = 5
DEFAULT_NEWDAY_SHIFT_MINUTES = 180
DEFAULT_MISSED_INTERVAL_MINUTES = 3
DEFAULT_MISSED_COLOR = "red"
DEFAULT_MISSED_BADGE = None
DEFAULT_ARRIVING_INTERVAL_MINUTES = 5
DEFAULT_ARRIVING_COLOR = "primary"
DEFAULT_ARRIVING_BADGE = "mdi:run"
DEFAULT_DEFAULT_COLOR = None
